Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.NetworkInformation;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplicationIceCreamProject.Data;
using WebApplicationIceCreamProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;
using WebApplicationIceCreamProject.Services;
using Microsoft.AspNetCore.Hosting;
using Microsoft.ML;
using Microsoft.ML.Data;

using CsvHelper;
using CsvHelper.Configuration;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using Microsoft.Extensions.Primitives;

namespace WebApplicationIceCreamProject.Controllers
{
    public class AdminController : Controller
    {

        private readonly IceCreamContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public AdminController(IceCreamContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }
        

        // GET: Admin
        public async Task<IActionResult> Index()
        {
              return _context.IceCream != null ? 
                          View(await _context.IceCream.ToListAsync()) :
                          Problem("Entity set 'AdminContext.IceCream'  is null.");
        }
        // GET: Orders/Edit/5
        public async Task<IActionResult> EditOrder(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            return View(order);
        }

        // POST: Orders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditOrder(int id, [Bind("Id,FirstName,LastName,PhoneNumber,Email,Street,City,HouseNumber,Products,Date,FeelsLike,Humidity,IsItHoliday,Day,Total")] Order order)
        {
            if (id != order.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(order);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderExists(order.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(OrdersList));
            }
            return View(order);
        }
        private bool OrderExists(int id)
        {
            return (_context.Order?.Any(e => e.Id == id)).GetValueOrDefault();
        }
        public async Task<IActionResult> OrderDetails(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }
            var orderItems = await _context.ShoppingCartItems.Where(item => item.OrderId == id).ToListAsync();
            //Bind order's products to the entity order
            order.Products = orderItems;

            return View(order);
        }
        // GET: Orders/Delete/5
        public async Task<IActionResult> DeleteOrder(int? id)
        {
            if (id == null || _context.Order == null)
            {
                return NotFound();
            }

            var order = await _context.Order
                .FirstOrDefaultAsync(m => m.Id == id);
            if (order == null)
            {
                return NotFound();
            }

            return View(order);
        }

        // POST: Orders/Delete/5
        [HttpPost, ActionName("DeleteOrder")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteOrder(int id)
        {
            if (_context.Order == null)
            {
                return Problem("Entity set 'IceCreamContext.Order'  is null.");
            }
            var order = await _context.Order.FindAsync(id);
            if (order != null)
            {
                var orderItems = await _context.ShoppingCartItems.Where(item => item.OrderId == order.Id).ToListAsync();
                foreach(var item in orderItems)
                {
                    _context.ShoppingCartItems.Remove(item);
                    await _context.SaveChangesAsync();
                }
                _context.Order.Remove(order);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(OrdersList));
        }

        public IActionResult OpenPage()
        {
            return View();
        }


        // GET: Admin/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.IceCream == null)
            {
                return NotFound();
            }

            var iceCream = await _context.IceCream
                .FirstOrDefaultAsync(m => m.Id == id);
            if (iceCream == null)
            {
                return NotFound();
            }

            return View(iceCream);
        }

        // GET: Admin/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Image_URL,Description,Price")] IceCream iceCream, IFormFile ImageFile)
        {
            if (ImageFile != null && ImageFile.Length > 0)
            {
                // Handle the case where the user uploads an image from the file explorer
                // Generate a unique filename for the image
                string uniqueFileName = $"{Guid.NewGuid().ToString()}_{DateTime.Now.Ticks}{Path.GetExtension(ImageFile.FileName)}.jpg";

                // Define the path where you want to save the image inside the wwwroot / images folder
                var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", uniqueFileName);

                using (var fileStream = new FileStream(imagePath, FileMode.Create))
                {
                    await ImageFile.CopyToAsync(fileStream);
                }

                // Update the Image_URL property with the new path (relative to wwwroot)
                iceCream.Image_URL = $"{uniqueFileName}";

                _context.Add(iceCream);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else if (!string.IsNullOrEmpty(iceCream.Image_URL))
            {
                // Handle the case where the user provides an image URL
                var imageUrl = iceCream.Image_URL;
                var isImageValid = await CheckIfImageIsValidAsync(imageUrl);

                if (!isImageValid)
                {
                    ModelState.AddModelError(string.Empty, "The provided image URL is not valid or does not contain a recognized ice cream image.");
                    return View(iceCream);
                }

                // Generate a unique filename for the image
                string uniqueFileName = $"{Guid.NewGuid().ToString()}_{DateTime.Now.Ticks}.jpg";

                // Define the path where you want to save the image inside the wwwroot / images folder
                var imagePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", uniqueFileName);

                // Download and save the image to the specified path
                using (var httpClient = new HttpClient())
                {
                    var response = await httpClient.GetAsync(imageUrl);

                    if (response.IsSuccessStatusCode)
                    {
                        var contentStream = await response.Content.ReadAsStreamAsync();

                        using (var fileStream = new FileStream(imagePath, FileMode.Create))
                        {
                            await contentStream.CopyToAsync(fileStream);
                        }

                        // Update the Image_URL property with the new path (relative to wwwroot)
                        iceCream.Image_URL = $"{uniqueFileName}";

                        _context.Add(iceCream);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            else
            {
                ModelState.AddModelError(string.Empty, "Please provide either an image URL or upload an image.");
                return View(iceCream);
            }

            // If ModelState is not valid, return the view with validation errors
            return View(iceCream);
        }


        private async Task<bool> CheckIfImageIsValidAsync(string imageUrl)
        {
            //Implement your logic to check if the image is valid(e.g., using your ApiService).
            //Return true if the image is valid, and false if it's not.
            var apiService = new ApiService("acc_e0d8ec2b70f224f");

Controllers/KafkaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Threading;
using System.Threading.Tasks;
using WebApplicationIceCreamProject.Data;
using Microsoft.Extensions.Configuration;
namespace WebApplicationIceCreamProject.Controllers
{

	//public class KafkaController : Controller
	//{
	//	private readonly KafkaConsumer kafkaConsumer;
	//	private CancellationTokenSource cancellationTokenSource;

	//	private readonly string connectionString = "AdminContext";

	//	public KafkaController()
	//	{
	//		kafkaConsumer = new KafkaConsumer(connectionString);
	//		cancellationTokenSource = new CancellationTokenSource();
	//	}

	// Your action methods
	public class KafkaController : Controller
	{
		private readonly KafkaConsumer kafkaConsumer;
		private CancellationTokenSource cancellationTokenSource;
		private readonly string connectionString;

		public KafkaController(IConfiguration configuration)
		{
			connectionString = configuration["ConnectionStrings:AdminContext"]; // Retrieve the connection string
			kafkaConsumer = new KafkaConsumer(connectionString); // Pass the connection string to the KafkaConsumer constructor
			cancellationTokenSource = new CancellationTokenSource();
		}





		//public class KafkaController : Controller

		//{
		//	private readonly KafkaConsumer kafkaConsumer;
		//private CancellationTokenSource cancellationTokenSource;
		//private readonly IceCreamContext dbContext;


		//public KafkaController(IceCreamContext dbContext)
		//{
		//	this.dbContext = dbContext;
		//	this.kafkaConsumer = new KafkaConsumer(dbContext);
		//	this.cancellationTokenSource = new CancellationTokenSource();
		//}

		//	private readonly KafkaConsumer kafkaConsumer;
		//	private readonly Func<IceCreamContext> _contextFactory;
		//	private CancellationTokenSource cancellationTokenSource;

		//	public KafkaController(Func<IceCreamContext> contextFactory)
		//	{
		//		_contextFactory = contextFactory;
		//		kafkaConsumer = new KafkaConsumer(_contextFactory);
		//		cancellationTokenSource = new CancellationTokenSource();
		//	}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult StartConsumer()
		{
			cancellationTokenSource = new CancellationTokenSource();
			Task.Run(() => kafkaConsumer.StartConsumerAsync(cancellationTokenSource.Token));
			return RedirectToAction("Index");
		}

		public IActionResult StopConsumer()
		{
			cancellationTokenSource.Cancel();
			return RedirectToAction("Index");
		}
		[HttpPost]
		
		public IActionResult StartSimulator()
		{
			try
			{
				cancellationTokenSource = new CancellationTokenSource();
				// Start Kafka consumer in the background
				Task.Run(() =>
				{
					try
					{
						kafkaConsumer.StartConsumerAsync(cancellationTokenSource.Token).GetAwaiter().GetResult();
					}
					catch (Exception ex)
					{
						Console.WriteLine($"Kafka Consumer Error: {ex.Message}");
					}
					finally
					{
						cancellationTokenSource.Dispose(); // Dispose the CancellationTokenSource
					}
				});
				return Ok(); // Return a success response
			}
			catch (Exception ex)
			{
				return BadRequest($"Failed to start Kafka Simulator: {ex.Message}");
			}
		}

		//public IActionResult StartSimulator()
		//{
		//	try
		//	{
		//		cancellationTokenSource = new CancellationTokenSource();
		//		// Start Kafka consumer in the background
		//		Task.Run(() => kafkaConsumer.StartConsumerAsync(cancellationTokenSource.Token));
		//		return Ok(); // Return a success response
		//	}
		//	catch (Exception ex)
		//	{
		//		return BadRequest($"Failed to start Kafka Simulator: {ex.Message}");
		//	}
		//}
	}


}
//using Microsoft.AspNetCore.Mvc;
//using WebApplicationIceCreamProject.Services;

//public class KafkaController : ControllerBase
//{
//	private readonly KafkaConsumerService kafkaConsumerService;

//	public KafkaController(KafkaConsumerService kafkaConsumerService)
//	{
//		this.kafkaConsumerService = kafkaConsumerService;
//	}

//	[HttpPost("/start-consumer")]
//	public IActionResult StartConsumer()
//	{
//		kafkaConsumerService.StartConsumer();
//		return Ok("Consumer started.");
//	}

//	[HttpPost("/stop-consumer")]
//	public IActionResult StopConsumer()
//	{
//		kafkaConsumerService.StopConsumer();
//		return Ok("Consumer stopped.");
//	}
//}

Views/Admin/OrdersList.cshtml
@model IEnumerable<WebApplicationIceCreamProject.Models.Order>

@{
	ViewData["Title"] = "Index";
	Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<div class="shilat" style="height: 210px">
	<div class="banner-content">
		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="text-content text-center">
						<span>@*<i class="icon icon-calendar mr-2"></i>*@ADMIN</span>
						<h2>Total Orders</h2>

						<div class="breadcum-items mt-2">
							@*      <span class="item color-primary" style="font-size: 15px;"><a asp-action="Home">Home /</a></span>
							<span class="item color-primary" style="font-size: 15px;">Flavors</span>

							*@
							<span class="item" style="font-size: 17px;"><a asp-action="OpenPage">Home /</a></span>

							<span class="item colored" style=" font-size: 17px;">Orders</span>
							<div>
								<button id="startConsumerButton" class="btn btn-primary">Start Kafka Consumer</button>
							</div>

						</div>

						<!-- ... Your main content ... -->
						<!-- Include JavaScript code to handle the button click -->
						<script>
							document.getElementById("startConsumerButton").addEventListener("click", function () {
								// Send an AJAX request to start the Kafka consumer
								fetch("/Kafka/StartSimulator", {
									method: "POST"
								})
									.then(response => {
										if (response.ok) {
											alert("Kafka consumer started successfully.");
										} else {
											alert("Failed to start the Kafka consumer.");
										}
									})
									.catch(error => {
										console.error("Error:", error);
										alert("An error occurred while starting the Kafka consumer.");
									});
							});
						</script>
						@*     <br />
						<br />
						<span class="item colored" style="font-size: 23px;">Add a Delicious New Flavor to Our Menu</span>*@

					</div>
				</div>
			</div>
		</div>
	</div>
</div><!--site-banner-->

<table class="table" style="background-color: #f5f5f5;">
	<thead>
		<tr style="color:#ce3c83;" class="text-center">
			<th>FirstName</th>
			<th>@Html.DisplayNameFor(model => model.LastName)</th>
			<th>
				@Html.DisplayNameFor(model => model.PhoneNumber)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Email)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Street)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.City)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.HouseNumber)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Date)
			</th>
			@*<th>
			@Html.DisplayNameFor(model => model.FeelsLike)
			</th>
			<th>
			@Html.DisplayNameFor(model => model.Humidity)
			</th>*@
			@*	<th>
			@Html.DisplayNameFor(model => model.IsItHoliday)
			</th>*@
			<th>
				@Html.DisplayNameFor(model => model.Day)
			</th>
			<th>
				@Html.DisplayNameFor(model => model.Total)
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (var item in Model)
		{
			<tr class="text-center">
				<td>
					@Html.DisplayFor(modelItem => item.FirstName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.LastName)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.PhoneNumber)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Email)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Street)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.City)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.HouseNumber)
				</td>

				<td>
					@Html.DisplayFor(modelItem => item.Date)
				</td>
				@*<td>
			@Html.DisplayFor(modelItem => item.FeelsLike)
			</td>
			<td>
			@Html.DisplayFor(modelItem => item.Humidity)
			</td>
			<td>
			@Html.DisplayFor(modelItem => item.IsItHoliday)
			</td>*@
				<td>
					@Html.DisplayFor(modelItem => item.Day)
				</td>
				<td>
					@Html.DisplayFor(modelItem => item.Total)
				</td>
				<td>
					<a asp-action="OrderDetails" asp-route-id="@item.Id"><strong>Details</strong></a> |
					<a asp-action="EditOrder" asp-route-id="@item.Id"><strong>Edit</strong></a> |
					<a asp-action="DeleteOrder" asp-route-id="@item.Id"><strong>Delete</strong></a>
				</td>
				@*<td>

			</td>*@
			</tr>
		}
	</tbody>
</table>
@* @section scripts {
	<script>
		$(document).ready(function () {
			$('#startSimulatorButton').click(function () {
				// Make an AJAX request to start the Kafka simulator
				$.ajax({
					url: '@Url.Action("StartSimulator", "Kafka")', // Replace with your controller and action names
					type: 'POST',
					success: function () {
						alert('Kafka Simulator started successfully.');
					},
					error: function () {
						alert('Failed to start Kafka Simulator.');
					}
				});
			});
		});
	</script>
}

<!-- Your button element -->
 <button id="startSimulatorButton" class="btn btn-primary">Start Kafka Simulator</button>
 *@

@*<div class="table-responsive"> ציפורה
	<table class="table table-hover">
		<thead>
			<tr>
				<th>ID</th>
				<th>First Name</th>
				<th>Last Name</th>
				<th>Date</th>
				<th>Total</th>
			</tr>
		</thead>
		<tbody>
			@foreach (var order in Model)
			{
				<tr>
					<td class="text-center">@order.Id</td>
					<td class="text-center">@order.FirstName</td>
					<td class="text-center">@order.LastName</td>
					<td class="text-center">@order.Date.Day/@order.Date.Month/@order.Date.Year</td>
					<td><span class="text-success">@order.Total.ToString("F2")$</span></td>
					<td>
						<a asp-action="Edit" asp-route-id="@order.Id">Edit</a> |
						<a asp-action="Details" asp-route-id="@order.Id">Details</a> |
						<a asp-action="Delete" asp-route-id="@order.Id">Delete</a>
					</td>
				</tr>
			}
		</tbody>
	</table>
</div>*@



@*<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Modernize Free</title>
	<link rel="shortcut icon" type="image/png" href="~/assets/images/logos/favicon.png" />
	<link rel="stylesheet" href="~/assets/css/styles.min.css" />
</head>*@
@*	<div class="col-lg-8 d-flex align-items-stretch">
		<div class="card w-100">
			<div class="card-body p-4">
				<h5 class="card-title fw-semibold mb-4">Recent Transactions</h5>
				<div class="table-responsive">
					<table class="table text-nowrap mb-0 align-middle">
						<thead class="text-dark fs-4">
							<tr>
								<th class="border-bottom-0">
									<h6 class="fw-semibold mb-0">Id</h6>
								</th>
								<th class="border-bottom-0">
									<h6 class="fw-semibold mb-0">Assigned</h6>
								</th>
								<th class="border-bottom-0">
									<h6 class="fw-semibold mb-0">Name</h6>
								</th>
								<th class="border-bottom-0">
									<h6 class="fw-semibold mb-0">Priority</h6>
								</th>
								<th class="border-bottom-0">
									<h6 class="fw-semibold mb-0">Budget</h6>
								</th>
							</tr>
						</thead>
						<tbody>
							<tr>
								<td class="border-bottom-0"><h6 class="fw-semibold mb-0">1</h6></td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-1">Sunil Joshi</h6>
									<span class="fw-normal">Web Designer</span>
								</td>
								<td class="border-bottom-0">
									<p class="mb-0 fw-normal">Elite Admin</p>
								</td>
								<td class="border-bottom-0">
									<div class="d-flex align-items-center gap-2">
										<span class="badge bg-primary rounded-3 fw-semibold">Low</span>
									</div>
								</td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-0 fs-4">$3.9</h6>
								</td>
							</tr>
							<tr>
								<td class="border-bottom-0"><h6 class="fw-semibold mb-0">2</h6></td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-1">Andrew McDownland</h6>
									<span class="fw-normal">Project Manager</span>
								</td>
								<td class="border-bottom-0">
									<p class="mb-0 fw-normal">Real Homes WP Theme</p>
								</td>
								<td class="border-bottom-0">
									<div class="d-flex align-items-center gap-2">
										<span class="badge bg-secondary rounded-3 fw-semibold">Medium</span>
									</div>
								</td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-0 fs-4">$24.5k</h6>
								</td>
							</tr>
							<tr>
								<td class="border-bottom-0"><h6 class="fw-semibold mb-0">3</h6></td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-1">Christopher Jamil</h6>
									<span class="fw-normal">Project Manager</span>
								</td>
								<td class="border-bottom-0">
									<p class="mb-0 fw-normal">MedicalPro WP Theme</p>
								</td>
								<td class="border-bottom-0">
									<div class="d-flex align-items-center gap-2">
										<span class="badge bg-danger rounded-3 fw-semibold">High</span>
									</div>
								</td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-0 fs-4">$12.8k</h6>
								</td>
							</tr>
							<tr>
								<td class="border-bottom-0"><h6 class="fw-semibold mb-0">4</h6></td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-1">Nirav Joshi</h6>
									<span class="fw-normal">Frontend Engineer</span>
								</td>
								<td class="border-bottom-0">
									<p class="mb-0 fw-normal">Hosting Press HTML</p>
								</td>
								<td class="border-bottom-0">
									<div class="d-flex align-items-center gap-2">
										<span class="badge bg-success rounded-3 fw-semibold">Critical</span>
									</div>
								</td>
								<td class="border-bottom-0">
									<h6 class="fw-semibold mb-0 fs-4">$2.4k</h6>
								</td>
							</tr>
						</tbody>
					</table>
				</div>
			</div>
		</div>
		<script src="~/assets/libs/jquery/dist/jquery.min.js"></script>
		<script src="~/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
		<script src="~/assets/js/sidebarmenu.js"></script>
		<script src="~/assets/js/app.min.js"></script>
		<script src="~/assets/libs/apexcharts/dist/apexcharts.min.js"></script>
		<script src="~/assets/libs/simplebar/dist/simplebar.js"></script>
	    <script src="~/assets/js/dashboard.js"></script>

	</div>*@


@*<div class="table-responsive scrollbar">
	<table class="table table-hover table-striped overflow-hidden">
	<thead>
	<tr>
	<th scope="col">Name</th>
	<th scope="col">Email</th>
	<th scope="col">Phone</th>
	<th scope="col">Address</th>
	<th scope="col">Status</th>
	<th class="text-end" scope="col">Amount</th>
	</tr>
	</thead>
	<tbody>
	<tr class="align-middle">
	<td class="text-nowrap">
	<div class="d-flex align-items-center">
	<div class="avatar avatar-xl">
	<img class="rounded-circle" src="../../assets/img/team/4.jpg" alt="" />
	</div>
	<div class="ms-2">Ricky Antony</div>
	</div>
	</td>
	<td class="text-nowrap">ricky@example.com</td>
	<td class="text-nowrap">(201) 200-1851</td>
	<td class="text-nowrap">2392 Main Avenue, Penasauka</td>
	<td><span class="badge badge rounded-pill d-block p-2 badge-subtle-success">Completed<span class="ms-1 fas fa-check" data-fa-transform="shrink-2"></span></span></td>
	<td class="text-end">$99</td>
	</tr>
	<tr class="align-middle">
	<td class="text-nowrap">
	<div class="d-flex align-items-center">
	<div class="avatar avatar-xl">
	<img class="rounded-circle" src="../../assets/img/team/13.jpg" alt="" />
	</div>
	<div class="ms-2">Emma Watson</div>
	</div>
	</td>
	<td class="text-nowrap">emma@example.com</td>
	<td class="text-nowrap">(212) 228-8403</td>
	<td class="text-nowrap">2289 5th Avenue, New York</td>
	<td><span class="badge badge rounded-pill d-block p-2 badge-subtle-success">Completed<span class="ms-1 fas fa-check" data-fa-transform="shrink-2"></span></span></td>
	<td class="text-end">$199</td>
	</tr>
	<tr class="align-middle">
	<td class="text-nowrap">
	<div class="d-flex align-items-center">
	<div class="avatar avatar-xl">
	<div class="avatar-name rounded-circle"><span>RA</span></div>
	</div>
	<div class="ms-2">Rowen Atkinson</div>
	</div>
	</td>
	<td class="text-nowrap">rown@example.com</td>
	<td class="text-nowrap">(201) 200-1851</td>
	<td class="text-nowrap">112 Bostwick Avenue, Jersey City</td>
	<td><span class="badge badge rounded-pill d-block p-2 badge-subtle-primary">Processing<span class="ms-1 fas fa-redo" data-fa-transform="shrink-2"></span></span></td>
	<td class="text-end">$755</td>
	</tr>
	<tr class="align-middle">
	<td class="text-nowrap">
	<div class="d-flex align-items-center">
	<div class="avatar avatar-xl">
	<img class="rounded-circle" src="../../assets/img/team/2.jpg" alt="" />
	</div>
	<div class="ms-2">Antony Hopkins</div>
	</div>
	</td>
	<td class="text-nowrap">antony@example.com</td>
	<td class="text-nowrap">(901) 324-3127</td>
	<td class="text-nowrap">3448 Ile De France St #242</td>
	<td><span class="badge badge rounded-pill d-block p-2 badge-subtle-secondary">On Hold<span class="ms-1 fas fa-ban" data-fa-transform="shrink-2"></span></span></td>
	<td class="text-end">$50</td>
	</tr>
	<tr class="align-middle">
	<td class="text-nowrap">
	<div class="d-flex align-items-center">
	<div class="avatar avatar-xl">
	<img class="rounded-circle" src="../../assets/img/team/3.jpg" alt="" />
	</div>
	<div class="ms-2">Jennifer Schramm</div>
	</div>
	</td>
	<td class="text-nowrap">jennifer@example.com</td>
	<td class="text-nowrap">(828) 382-9631</td>
	<td class="text-nowrap">659 Hannah Street, Charlotte</td>
	<td><span class="badge badge rounded-pill d-block p-2 badge-subtle-warning">Pending<span class="ms-1 fas fa-stream" data-fa-transform="shrink-2"></span></span></td>
	<td class="text-end">$150</td>
	</tr>
	</tbody>
	</table>
	</div>*@